In [3]:
import pandas as pd
dataset = pd.read_excel("Dry_Bean_Dataset.xlsx") #pd.read_csv (if file in csv extension)

In [4]:
dataset.head(5)

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0  28395    610.291       208.178117       173.888747      1.197191   
1  28734    638.018       200.524796       182.734419      1.097356   
2  29380    624.110       212.826130       175.931143      1.209713   
3  30008    645.884       210.557999       182.516516      1.153638   
4  30140    620.134       201.847882       190.279279      1.060798   

   Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0      0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1      0.411785       29172     191.272750  0.783968  0.984986   0.887034   
2      0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3      0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4      0.333680       30417     195.896503  0.773098  0.990893   0.984877   

   Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  Class  
0     0.913358      0.007332      0.003147      0.834222      0.998724  SEKER  
1     0.953861      0.006979      0.003564      0.909851      0.998430  SEKER  
2     0.908774      0.007244      0.003048      0.825871      0.999066  SEKER  
3     0.928329      0.007017      0.003215      0.861794      0.994199  SEKER  
4     0.970516      0.006697      0.003665      0.941900      0.999166  SEKER

In [5]:
dataset.isna().sum() #cek null values

Area               0
Perimeter          0
MajorAxisLength    0
MinorAxisLength    0
AspectRation       0
Eccentricity       0
ConvexArea         0
EquivDiameter      0
Extent             0
Solidity           0
roundness          0
Compactness        0
ShapeFactor1       0
ShapeFactor2       0
ShapeFactor3       0
ShapeFactor4       0
Class              0
dtype: int64

In [6]:
dataset.iloc[:, -1].nunique() #cek banyak kelas untuk target class

7

# Preprocessing

In [7]:
x = dataset.iloc[:, :-1].values #independent variabel
y = dataset.iloc[:, -1].values #dependent variabel

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print (y)

[5 5 5 ... 3 3 3]


In [12]:
#split data testing dan data training
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #StandarScaler().fit_transform(X_train)
X_test = sc.transform(X_test)

# Algoritma

Naive Bayes

In [16]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [19]:
import numpy as np
y_pred = classifier.predict(X_test)
print("[Hasil Prediksi,", "Hasil Latih]")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[Hasil Prediksi, Hasil Latih]
[[3 3]
 [3 3]
 [3 3]
 ...
 [3 3]
 [3 3]
 [1 1]]


In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Hasil Akurasi :", accuracy_score(y_test, y_pred))

[[259   0  40   0   2   3  15]
 [  0 111   0   0   0   0   0]
 [ 35   0 377   0   5   1   1]
 [  0   0   0 808   2  19  76]
 [  0   0  10   4 469   0   8]
 [  2   0   0   3   0 442  23]
 [  4   0   1  57  18  10 598]]
Hasil Akurasi : 0.9003820158683514


Decision Tree

In [23]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [24]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [3 3]
 [3 3]
 ...
 [3 3]
 [3 3]
 [1 1]]


In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Hasil Akurasi Model Decision Tree")
accuracy_score(y_test, y_pred)

[[285   0  20   0   3   5   6]
 [  2 109   0   0   0   0   0]
 [ 24   0 384   0   8   1   2]
 [  0   0   0 822   2  18  63]
 [  2   0  10   5 457   0  17]
 [  3   0   0   6   0 442  19]
 [  6   0   3  75  14   4 586]]
Hasil Akurasi Model Decision Tree


0.9065530414340288